project:
  type: book

book:
  title: "Introduction to programming for data science"
  subtitle: "STAT 201"
  author: "Arvind Krishna"
  date: "9/20/2022"
  
  sidebar:
    search: true
    logo: "NU_Stat_logo.png"
    logo-href: "https://statistics.northwestern.edu/"
    
  chapters:
    - index.qmd
    - Rintro.qmd
  appendices: 
    - Datasets.ipynb

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

execute:
  freeze: auto

