project:
  type: book

book:
  title: "Regression analysis (R notes)"
  subtitle: "STAT 350"
  author: "Arvind Krishna"
  date: "9/20/2023"
  
  sidebar:
    search: true
    logo: "NU_Stat_logo.png"
    logo-href: "https://statistics.northwestern.edu/"
    
  chapters:
    - index.qmd
    - Rintro.qmd
  appendices: 
    - Assignment A.qmd
    - Datasets.ipynb

bibliography: references.bib

format:
  html:
    theme: cosmo

freeze:
    auto

