project:
  type: book

book:
  title: "Regression analysis (R notes)"
  subtitle: "STAT 350"
  author: "Arvind Krishna"
  date: "9/20/2023"
  
  sidebar:
    search: true
    logo: "NU_Stat_logo.png"
    logo-href: "https://statistics.northwestern.edu/"
    
  chapters:
    - index.qmd
    - Rintro.qmd
    - t_test_example.qmd
    - SLR_model.qmd
    - Diagnostics_Remedial_Measures.qmd
    - Diagnostics_Remedial_Measures_MLR.qmd
    - multicollinearity.qmd
    - quant_qual_preds.qmd
  appendices: 
    - Assignment A.qmd
    - Assignment B.qmd
    - Assignment C.qmd
    - Assignment D.qmd
    - Datasets.ipynb

bibliography: references.bib

format:
  html:
    theme: cosmo

freeze:
    auto

